# Generated by Django 3.1.1 on 2021-03-05 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('isBOIsalary', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=255)),
                ('invoiceNumber', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('invoiceDate', models.DateField()),
                ('paymentDate', models.DateField(null=True)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Revenues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReceived', models.DateField()),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dash.invoice')),
            ],
        ),
    ]
